source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"
pod "DOPDropDownMenu-Enhanced"
pod "Masonry"
pod "SDCycleScrollView"
pod "LTNavigationBar"
pod "DACircularProgress"
pod "pop"

target :"GFBS"
